apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      name: {{ .Release.Name }}-api
      labels:
        app: {{ .Release.Name }}-api
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-api
          image: "{{ .Values.image.name }}:{{ .Values.image.tag
          imagePullPolicy: {{ .Values.image.policy }}
          command:
            - /bin/sh
            - -c
          args:
            - uvicorn kubernetes_playground.main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: {{ .Values.service.port.container }}
              name: {{ .Values.service.port.name }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.service.port.container }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.port.container }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
---
