image:
  name: thetelematic95/kubernetes_playground
  tag: latest
  policy: IfNotPresent

api:
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

service:
  port:
    container: 8000
    name: http
    exposed: 8888

ingress:
  enabled: true
  ingressClassName: "traefik"
  hostname: "raspberry.local"

config:
  LOG_LEVEL: "INFO"
