image:
  name: thetelematic95/raspberry_playground
  tag: latest
  policy: Always

api:
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

service:
  port:
    container: 8000
    name: http
    exposed: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "raspberry.local"

config:
  LOG_LEVEL: "INFO"
